spring:
  sql:
    init:
      mode: always
  config:
    import:
      - optional:file:.env[.properties]
  security:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME}:${POSTGRESQL_PORT}/${POSTGRESQL_DB_NAME}
    username: ${POSTGRESQL_DB_USER}
    password: ${POSTGRESQL_DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: DEBUG
server:
  port: 8080
